source 'https://rubygems.org'

gem 'gooddata'
gem 'ffi', '1.9.3'
gem "gooddata-dss-jdbc",:platform => "jruby"
gem "gooddata_connectors_base", :path => 'gooddata_connectors_base-s3'
gem "gooddata_connectors_metadata", :path => "gooddata_connectors_metadata-bds_implementation"
gem "gooddata_connectors_downloader_salesforce", :path => "gooddata_connectors_downloader_salesforce-gse"