source 'https://rubygems.org'

gem 'ffi','1.9.3'
gem 'gooddata'
gem "gooddata-dss-jdbc",:platform => "jruby"
gem "gooddata_connectors_base", :path => 'gooddata_connectors_base-s3'
gem "gooddata_connectors_metadata", :path => "gooddata_connectors_metadata-bds_implementation"
gem "gooddata_connectors_ads", :path => "gooddata_connectors_ads-0.0.1"
