source 'https://rubygems.org'
 
gem 'gooddata', :path => 'vendor/gooddata-ruby'
gem 'ffi', '1.9.3', :platform => 'jruby'
gem 'user_hierarchies', :path => 'vendor/user_hierarchies'
gem 'gooddata_datawarehouse', :platform => 'jruby'


